### ISSUE TITLE
Portfolio: Application Deploy

### ISSUE THREAD

**Issue by PrantoshB** [PrantoshB/Portfolio#9]
- Here's the link to the deployed page of my Portfolio: https://prantoshb.github.io/Portfolio/

**Comment by mckent05** [comment]
Hi @PrantoshB,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/200296269-bf59713e-f039-4f00-8b66-c1429e9750c5.gif)

## Highlights
- Your portfolio is properly deployed ✔️ ✔️ 
- Your project looks good 👍 👍 


## Required Changes ♻️
- Please update your Readme file with your live link to make it easier to access your page 👍 👍 
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PrantoshB** [comment]
Hello @mckent05, I hope you're doing well.

I have already added the live link saying "Live Demo Link". Please look into that.
Thanks 😄

**Comment by omarsalem7** [comment]
Hi @PrantoshB 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
